print("Hello, World!")
print("Welcome to mysuru!")
print("Enjoy your stay here.")
print("Don't forget to visit the palaces and gardens.")
print("Have a great day!")
print("Goodbye!")
print("See you again soon!")
print("Take care!")
print("Stay safe!")
print("Happy travels!")